### ISSUE TITLE
Acestream engine raspberry

### ISSUE THREAD

**Issue by francescosoft** [tarasian666/acestream#1]
Hello,

Is this the acestream engine for raspberry ?

Will it work whithout a pc ?

Thanks,

Francesco

**Comment by tarasian666** [comment]
Yes, it is complete engine, it will work without pc on raspberry with any linux distro, just install python dependencies 
python-apsw python-m2crypto python-setuptools(maybe not needed) python-pyamf

**Comment by francescosoft** [comment]
Cool ;)

Thank you for your answer.
Is there some readme for installation instructions ? A detailed howto would be nice :)

**Comment by tarasian666** [comment]
To run add execute permission to file start.py and execute this file.
This all is unpacked acestream with some bugfixes and without support from acestream team.

**Comment by francescosoft** [comment]
Thx :)
