### ISSUE TITLE
Can you please update for acestream 3.0

### ISSUE THREAD

**Issue by boygiandi** [tarasian666/acestream#5]
I have just installed acestream on centos 7, http://wiki.acestream.org/wiki/index.php/AceStream_3.0/en

I can start your script , but can't get video info from acestreamengine , I tried to get info by manual. Server acestream started but reply nothing

curl 'http://127.0.0.1:6878/LOAD/PID=3ad1b30e6bba6c4afda7096fbf15645b65d3b605'
curl: (52) Empty reply from server

Can you please check

**Comment by tarasian666** [comment]
Sorry, i can't. I'm not part of acestream company.
Few years ago this code anyone could extract from package. 
I just posted it here to prevent it from disappearing.
It was made using opensource code parts so it must stay opensource. 
Acestream company making all to make this code closed.
